name: Further Testings

on: [push, pull_request]

jobs:

  chartTests:
    name: Helm Chart Tests
    if: ${{ !contains(github.event.head_commit.message, 'Skip Helm E2E Tests') || (github.event_name == 'push' && contains(github.ref, 'refs/tags/')) }}
    steps:
    - name: TestBaby  
      run: |
        echo "Issue title: ${{ github.event.head_commit.message }}"
