name: Further Testings

on: [push, pull_request]

jobs:

  chartTests:
    name: Helm Chart Tests
    if: github.event.label.name == 'bug'
    steps:
    - name: TestBaby  
      run: |
        echo "Issue title: ${{ github.event.head_commit.message }}"
